version: '3'
services:
 selenoid:
   network_mode: bridge
   image: aerokube/selenoid:1.11.0
   volumes:
     - "/d/Aerocub:/etc/selenoid/"
     - "/docker:/etc/selenoid"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "/d/docker/video:/opt/selenoid/video"
     - "/d/docker/logs:/opt/selenoid/logs"
     - "/d/docker/downloadsFiles:/home/selenium/Downloads"
   environment:
     - OVERRIDE_VIDEO_OUTPUT_DIR=/d/docker/video
   command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-capture-driver-logs", "-save-all-logs"]
   ports:
     - "4444:4444"

 selenoid-ui:
   image: "aerokube/selenoid-ui:1.10.10"
   network_mode: bridge
   links:
     - selenoid
   ports:
     - "8080:8080"
   command: ["--selenoid-uri", "http://selenoid:4444"]
